changelogFile=changelog.xml
# changelogFile=example-changelog.xml
# changelogFile=example-changelog.databricks.sql


url=jdbc:databricks://dbc-cd87d010-a2ab.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/0ae1c5691107a0a2;ConnCatalog=amalik_demo;
username=token
password=<token>


liquibase.reports.enabled=true
liquibase.reports.path=reports
liquibase.reports.open=false
# liquibase.dbclhistory.enabled=true
# liquibase.pro.globalStripComments=false
# liquibase.logLevel=FINE

# Change Intelligence parameters:
liquibase.platform.enabled=true
liquibase.platform.apiUrl=https://localhost/api
liquibase.platform.apiKey=liq_MVRzgokfuKVVPlYxJlrttbvjSruTPdwMJOYlYGiymKWOgizKnRjQGjMoxzQWsmOR
liquibase.platform.changelogIdentifier=mz-changelog
liquibase.platform.connectionIdentifier=mz-dev


liquibase.command.autoUpdate=off
